"""Small PostgreSQL adapter for the ledger's parameterized SQL.

SQLite remains the local default. PostgreSQL connections use autocommit for
reads and explicit transactions for writes. A transaction-scoped advisory lock
serializes this small, single-coordinator ledger across serverless instances.
"""
from __future__ import annotations

import re

import psycopg
from psycopg.pq import TransactionStatus
from psycopg.rows import dict_row

WRITE_LOCK = 4603371


class PostgresConnection:
    def __init__(self, url: str):
        self.raw = psycopg.connect(url, autocommit=True, row_factory=dict_row, connect_timeout=10)

    def execute(self, sql, params=()):
        # All statements are application-owned; values always remain parameters.
        return self.raw.execute(sql.replace("?", "%s"), params)

    def executemany(self, sql, rows):
        with self.raw.cursor() as cursor:
            cursor.executemany(sql.replace("?", "%s"), rows)

    def initialize(self, sqlite_schema: str):
        schema = re.sub(r"INTEGER\s+PRIMARY KEY", "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY", sqlite_schema)
        schema = schema.replace("REAL", "DOUBLE PRECISION")
        schema = schema.replace("(datetime('now'))", "(CURRENT_TIMESTAMP::text)")
        self.begin_write()
        try:
            self.raw.execute(schema)
            self.commit()
        except Exception:
            self.rollback()
            raise

    def begin_write(self):
        self.raw.execute("BEGIN")
        self.raw.execute("SELECT pg_advisory_xact_lock(%s)", (WRITE_LOCK,))

    @property
    def in_transaction(self):
        return self.raw.info.transaction_status != TransactionStatus.IDLE

    def commit(self):
        self.raw.commit()

    def rollback(self):
        self.raw.rollback()

    def close(self):
        self.raw.close()

    def reset_sequences(self):
        # Imported IDs are explicit, so advance each identity before manual writes.
        for table in ("berths", "vessels", "reservations", "annotations", "import_issues", "tours"):
            self.raw.execute(
                f"SELECT setval(pg_get_serial_sequence('{table}', 'id'), "
                f"COALESCE(MAX(id), 1), MAX(id) IS NOT NULL) FROM {table}"
            )
